export const sectors = [
   { value: 1, text: "Biyoteknoloji, Biyomedikal" },
   { value: 2, text: "Coğrafi Bilgi Sistemleri" },
   { value: 3, text: "Denizcilik" },
   { value: 4, text: "Diğer" },
   { value: 5, text: "Eğitim" },
   { value: 6, text: "Elektrik-Elektronik" },
   { value: 7, text: "Endüstriyel Otomasyon" },
   { value: 8, text: "Enerji" },
   { value: 9, text: "Finans, Bankacılık" },
   { value: 10, text: "Geri Dönüşüm" },
   { value: 11, text: "Havacılık" },
   { value: 12, text: "İklimlendirme" },
   { value: 13, text: "İletişim, Haberleşme" },
   { value: 14, text: "Kozmetik" },
   { value: 15, text: "Madencilik" },
   { value: 16, text: "Makine, Teçhizat, İmalat" },
   { value: 17, text: "Malzeme, Metalurji" },
   { value: 18, text: "Medya, Eğlence" },
   { value: 19, text: "Otomotiv" },
   { value: 20, text: "Petrol, Kimya" },
   { value: 21, text: "Robotik" },
   { value: 22, text: "Sağlık, Tıbbi Malzeme" },
   { value: 23, text: "Savunma Sanayi" },
   { value: 24, text: "Tarım, Gıda" },
   { value: 25, text: "Tekstil" },
   { value: 26, text: "Tıbbi Bilişim" },
   { value: 27, text: "Ulaştırma" },
   { value: 28, text: "Yapay Zeka" },
   { value: 29, text: "Yazılım" },
   { value: 30, text: "Yenilenebilir Enerji" },
   { value: 31, text: "Oyun" },
]